spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 737523983643-vor7bt96e14vk4avae0fdcqtj7vbfssq.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile,email